# Generated by Django 5.2.14 on 2026-05-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('greeting_text', models.CharField(max_length=255)),
                ('role_title', models.CharField(max_length=200)),
                ('hero_image_url', models.URLField(blank=True, max_length=500)),
                ('about_me_text', models.TextField()),
                ('about_me_image_url', models.URLField(blank=True, max_length=500)),
                ('what_i_do_text', models.TextField()),
                ('what_i_do_image_url', models.URLField(blank=True, max_length=500)),
                ('cv_file_url', models.URLField(blank=True, max_length=500)),
                ('contact_email', models.EmailField(max_length=254)),
                ('github_link', models.URLField(blank=True, max_length=500)),
                ('linkedin_link', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Profile info',
                'verbose_name_plural': 'Profile info',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('DevOps', 'DevOps'), ('AI', 'AI')], max_length=50)),
                ('icon_class_or_url', models.CharField(blank=True, max_length=255)),
                ('proficiency_percentage', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('live_demo_url', models.URLField(blank=True, max_length=500)),
                ('github_repo_url', models.URLField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('technologies_used', models.ManyToManyField(blank=True, related_name='projects', to='api.skill')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
